"""removed sender name and email and added country code

Revision ID: 05a277a7468e
Revises: cf778aa3c8a7
Create Date: 2026-07-26 17:30:49.181366

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05a277a7468e'
down_revision: str | Sequence[str] | None = 'cf778aa3c8a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_submissions_country_code'), 'submissions', ['country_code'], unique=False)
    op.drop_column('submissions', 'sender_email')
    op.drop_column('submissions', 'sender_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('sender_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('sender_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_submissions_country_code'), table_name='submissions')
    op.drop_column('submissions', 'country_code')
    # ### end Alembic commands ###
