"""edited form table columns, honeypot, ispublished

Revision ID: 0f8173240854
Revises: ff0cd310e130
Create Date: 2026-07-18 21:20:44.286002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8173240854'
down_revision: Union[str, Sequence[str], None] = 'ff0cd310e130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('honeypot', sa.String(length=36), nullable=True))
    op.drop_column('forms', 'schema_definition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('schema_definition', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('forms', 'honeypot')
    # ### end Alembic commands ###
