"""updated subscription table with submission used and storage bytes used

Revision ID: 14ab206e2ddd
Revises: 74ada54af975
Create Date: 2026-07-09 01:01:29.909748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ab206e2ddd'
down_revision: Union[str, Sequence[str], None] = '74ada54af975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
