"""edited form table

Revision ID: 1d6a45e3c9ad
Revises: 6063b463c136
Create Date: 2026-07-12 21:18:36.024410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6a45e3c9ad'
down_revision: Union[str, Sequence[str], None] = '6063b463c136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('name', sa.String(length=150), nullable=False))
    op.drop_column('forms', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('forms', 'name')
    # ### end Alembic commands ###
