"""added two feilds in form and one in submissions and rename one in submissions

Revision ID: 303d3e9bdc6f
Revises: b45b35d9fec7
Create Date: 2026-07-29 00:55:01.064905

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '303d3e9bdc6f'
down_revision: str | Sequence[str] | None = 'b45b35d9fec7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
