"""added default captchas to altcha in form

Revision ID: 38a0018b2fbd
Revises: b71ca6f3ed48
Create Date: 2026-07-18 23:42:47.964241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a0018b2fbd'
down_revision: Union[str, Sequence[str], None] = 'b71ca6f3ed48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
