"""added default captchas to altcha in form

Revision ID: 4a65e6d6d86b
Revises: 1b49f6e79b4a
Create Date: 2026-07-18 23:20:04.945522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a65e6d6d86b'
down_revision: Union[str, Sequence[str], None] = '1b49f6e79b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
