"""added captchas to form

Revision ID: 54ef8097507c
Revises: 6c1ead9b4759
Create Date: 2026-07-18 23:02:13.353802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ef8097507c'
down_revision: Union[str, Sequence[str], None] = '6c1ead9b4759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE captchatype AS ENUM ('altcha', 'cloudflare_turnstile');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('captcha_type', sa.Enum('ALTCHA', 'TURNSTILE', name='captchatype'), server_default='cloudflare_turnstile', nullable=False))
    op.add_column('forms', sa.Column('turnstile_sitekey', sa.String(length=255), nullable=True))
    op.add_column('forms', sa.Column('turnstile_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'turnstile_secret')
    op.drop_column('forms', 'turnstile_sitekey')
    op.drop_column('forms', 'captcha_type')
    
    # ### end Alembic commands ###
