"""add tables Processed Webhook Overage, form

Revision ID: 6063b463c136
Revises: 4c3cf2c7c07a
Create Date: 2026-07-11 17:18:09.514321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6063b463c136'
down_revision: Union[str, Sequence[str], None] = '4c3cf2c7c07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
