"""updated subscription table with submission used and storage bytes used

Revision ID: 74ada54af975
Revises: 15b5f48e9738
Create Date: 2026-07-09 00:55:47.911585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ada54af975'
down_revision: Union[str, Sequence[str], None] = '15b5f48e9738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('submissions_used', sa.Integer(), nullable=True))
    op.execute("UPDATE subscriptions SET submissions_used = 0")
    op.alter_column("subscriptions", "submissions_used", nullable=False)
    op.add_column('subscriptions', sa.Column('storage_bytes_used', sa.Integer(), nullable=True))
    op.execute("UPDATE subscriptions SET storage_bytes_used = 0")
    op.alter_column("subscriptions", "storage_bytes_used", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'storage_bytes_used')
    op.drop_column('subscriptions', 'submissions_used')
    # ### end Alembic commands ###
