"""removed heading from form settings

Revision ID: 74ff3ae2c739
Revises: 5481cd4cb6ce
Create Date: 2026-09-04 22:40:19.420304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ff3ae2c739'
down_revision: Union[str, Sequence[str], None] = '5481cd4cb6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'heading')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.add_column('forms', sa.Column('heading', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
