"""added new table for overusage Overage

Revision ID: 9d4ef8546dce
Revises: 14ab206e2ddd
Create Date: 2026-07-09 01:09:14.377352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4ef8546dce'
down_revision: Union[str, Sequence[str], None] = '14ab206e2ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overage_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('submission_blocks', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('billed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overage_charges')
    # ### end Alembic commands ###
