"""added few tables for auth and ratelimiting.

Revision ID: a20ea69766f1
Revises: c8467166f89a
Create Date: 2026-08-13 17:30:36.926825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a20ea69766f1'
down_revision: Union[str, Sequence[str], None] = 'c8467166f89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("token_type IN ('whitelist', 'blacklist')", name='ck_auth_tokens_token_type'),
    sa.PrimaryKeyConstraint('jti'),
    prefixes=['UNLOGGED']
    )
    op.create_index('ix_auth_tokens_expires_at', 'auth_tokens', ['expires_at'], unique=False)
    op.create_index('ix_auth_tokens_user_id', 'auth_tokens', ['user_id'], unique=False)
    op.create_table('rate_limit_buckets',
    sa.Column('bucket_key', sa.String(), nullable=False),
    sa.Column('window_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key', 'window_start'),
    prefixes=['UNLOGGED']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit_buckets')
    op.drop_index('ix_auth_tokens_user_id', table_name='auth_tokens')
    op.drop_index('ix_auth_tokens_expires_at', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
