"""added one column for submission whether opened or not

Revision ID: b028abf4172a
Revises: 303d3e9bdc6f
Create Date: 2026-08-01 00:36:19.113527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b028abf4172a'
down_revision: Union[str, Sequence[str], None] = '303d3e9bdc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column as nullable first so existing rows don't fail
    op.add_column("submissions", sa.Column("opened", sa.Boolean(), nullable=True))

    # 2. Update all existing rows to True
    op.execute("UPDATE submissions SET opened = true WHERE opened IS NULL")

    # 3. Alter the column to be NOT NULL now that it is populated
    op.alter_column("submissions", "opened", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'opened')
    # ### end Alembic commands ###
