"""added two feilds in form and one in submissions and rename one in submissions

Revision ID: b45b35d9fec7
Revises: 05a277a7468e
Create Date: 2026-07-29 00:04:42.572420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45b35d9fec7'
down_revision: Union[str, Sequence[str], None] = '05a277a7468e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('duplicate_allowed', sa.Boolean(), nullable=False))
    op.add_column('forms', sa.Column('duplicate_check_input', sa.String(length=100), nullable=True))
    op.add_column('submissions', sa.Column('note', sa.String(length=200), nullable=True))
    op.add_column('submissions', sa.Column('country', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_submissions_country_code'), table_name='submissions')
    op.create_index(op.f('ix_submissions_country'), 'submissions', ['country'], unique=False)
    op.drop_column('submissions', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_submissions_country'), table_name='submissions')
    op.create_index(op.f('ix_submissions_country_code'), 'submissions', ['country_code'], unique=False)
    op.drop_column('submissions', 'country')
    op.drop_column('submissions', 'note')
    op.drop_column('forms', 'duplicate_check_input')
    op.drop_column('forms', 'duplicate_allowed')
    # ### end Alembic commands ###
