"""added default captchas to altcha in form

Revision ID: b71ca6f3ed48
Revises: 4a65e6d6d86b
Create Date: 2026-07-18 23:40:01.099663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71ca6f3ed48'
down_revision: Union[str, Sequence[str], None] = '4a65e6d6d86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
