"""adding value to trial

Revision ID: cf778aa3c8a7
Revises: 743337b5e4bb
Create Date: 2026-07-26 03:26:02.888175

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'cf778aa3c8a7'
down_revision: str | Sequence[str] | None = '743337b5e4bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
