"""added column message, text col, bg color , and link color or form table

Revision ID: e1509a12d57e
Revises: 0f8173240854
Create Date: 2026-07-18 22:40:02.381241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1509a12d57e'
down_revision: Union[str, Sequence[str], None] = '0f8173240854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('sub_message', sa.String(length=200), server_default='Submission successful!', nullable=False))
    op.add_column('forms', sa.Column('sub_bg_color', sa.String(length=7), server_default='#ffffff', nullable=False))
    op.add_column('forms', sa.Column('sub_txt_color', sa.String(length=7), server_default='#000000', nullable=False))
    op.add_column('forms', sa.Column('sub_lnk_color', sa.String(length=7), server_default='#3b82f6', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'sub_lnk_color')
    op.drop_column('forms', 'sub_txt_color')
    op.drop_column('forms', 'sub_bg_color')
    op.drop_column('forms', 'sub_message')
    # ### end Alembic commands ###
