"""added column form subject and mail body

Revision ID: e903a5e9b7b3
Revises: 16aa755dacc1
Create Date: 2026-08-07 00:54:25.495735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e903a5e9b7b3'
down_revision: Union[str, Sequence[str], None] = '16aa755dacc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('customer_subject', sa.String(length=255), server_default='Submission Recieved.', nullable=False))
    op.add_column('forms', sa.Column('customer_body', sa.Text(), server_default='Hi,\n\nThank you for reaching out! We received your submission.', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'customer_body')
    op.drop_column('forms', 'customer_subject')
    # ### end Alembic commands ###
