"""edited form table

Revision ID: e9ac292e63ee
Revises: 1d6a45e3c9ad
Create Date: 2026-07-12 23:00:01.531503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ac292e63ee'
down_revision: Union[str, Sequence[str], None] = '1d6a45e3c9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('public_id', sa.String(length=8), nullable=False))
    op.create_index(op.f('ix_forms_public_id'), 'forms', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_public_id'), table_name='forms')
    op.drop_column('forms', 'public_id')
    # ### end Alembic commands ###
