"""is_published is now is_active from project

Revision ID: feaf031d11c6
Revises: 901885be491c
Create Date: 2026-07-21 23:46:41.149892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feaf031d11c6'
down_revision: Union[str, Sequence[str], None] = '901885be491c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Rename the column instead of dropping and adding it
    op.alter_column("forms", "is_published", new_column_name="is_active")

    # 2. Your other generated submissions updates
    op.add_column(
        "submissions",
        sa.Column(
            "status", sa.String(length=20), server_default="accepted", nullable=False
        ),
    )
    op.add_column(
        "submissions", sa.Column("spam_provider", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "submissions", sa.Column("sender_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "submissions", sa.Column("sender_email", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_submissions_spam_provider"),
        "submissions",
        ["spam_provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_status"), "submissions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_status"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_spam_provider"), table_name="submissions")
    op.drop_column("submissions", "sender_email")
    op.drop_column("submissions", "sender_name")
    op.drop_column("submissions", "spam_provider")
    op.drop_column("submissions", "status")

    # Revert the rename back to is_published
    op.alter_column("forms", "is_active", new_column_name="is_published")
    # ### end Alembic commands ###
