"""edited form table mapp the submissions

Revision ID: ff0cd310e130
Revises: 4f3ffcd9991a
Create Date: 2026-07-16 11:57:50.055641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0cd310e130'
down_revision: Union[str, Sequence[str], None] = '4f3ffcd9991a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('forms', sa.Column('allowed_domains', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('forms', sa.Column('redirect_url', sa.String(length=2083), nullable=True))
    op.add_column('forms', sa.Column('notification_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'notification_email')
    op.drop_column('forms', 'redirect_url')
    op.drop_column('forms', 'allowed_domains')
    op.drop_table('submissions')
    # ### end Alembic commands ###
